install.packages("leaflet")
install.packages("readr") 
install.packages("pryr") 
install.packages("dplyr") 
install.packages("ggplot2") 
install.packages("leaflet") 
install.packages("leaflet.providers")
install.packages("shiny") 
install.packages("rnaturalearth") 
install.packages("rnaturalearthdata" 
install.packages("raster") 
install.packages("sf") 
install.packages("tidyverse")
install.packages("terra") 
install.packages("rgbif") 
install.packages("DT") 
install.packages("reactable")
install.packages("plotly") 
install.packages("RColorBrewer")
install.packages("pdfetch")
install.packages("rmarkdown")
install.packages("htmlTable") 
install.packages("webshot")
install.packages("pagedown")



